In [1]:
import pandas as pd
# Tree Canopy Metric Dataset reflects 2019 tree canopy area
df = pd.read_csv('PARCELS_Tree_Canopy_Metrics.csv')

/Users/rachelyoung/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/Users/rachelyoung/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/var/folders/3k/5zd1hcfd4jv0bjvll1h2r7kr0000gn/T/ipykernel_12003/3114602732.py:3: DtypeWarning: Columns (4,6,12,14,18,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('PARCELS_Tree_Canopy_Metrics.csv')

# 1. What percentage of Boston's tree canopy is located on public land versus residential parcels?

**Dataset:** https://bostonopendata-boston.opendata.arcgis.com/datasets/boston::canopy-change-assessment-tree-canopy-metrics/about?layer=4

In [2]:
df.head()

,FID,FID_Boston,BOSTON_LAN,FID_COB_FY,PID,CM_ID,GIS_ID,OWNER,ST_NUM,ST_NAME,...,TC_Pv_A,TC_Land_A,TC_Pi_A,TC_P_A,TC_E_P,TC_Pv_P,TC_P_P,TC_Pi_P,Shape__Area,Shape__Length
0,1,1,1,-1,,,,,,,...,5717593,218739022,38429015,44146608,18.670309,2.613888,20.182319,17.568431,2.244137e+08,8.914611e+06
1,2,1,1,1,0100001000,,0100001000,PASCUCCI CARLO,104 A 104,PUTNAM,...,0,1237,13,13,0.404204,0.000000,1.050930,1.050930,1.233845e+03,1.594376e+02
2,3,1,1,2,0100002000,,0100002000,ATANASOV DANIEL,197,LEXINGTON,...,0,1162,242,242,0.000000,0.000000,20.826162,20.826162,1.161436e+03,1.566642e+02
3,4,1,1,3,0100003000,,0100003000,CHEVARRIA ANA S,199,LEXINGTON,...,1,1144,211,212,0.699301,0.087413,18.531469,18.444056,1.145411e+03,1.558082e+02
4,5,1,1,4,0100004000,,0100004000,"MADDALENI JAMES E, TS",201,LEXINGTON,...,106,1191,102,208,0.587741,8.900084,17.464316,8.564232,1.192610e+03,1.571514e+02

In [3]:
df.columns

Index(['FID', 'FID_Boston', 'BOSTON_LAN', 'FID_COB_FY', 'PID', 'CM_ID',
       'GIS_ID', 'OWNER', 'ST_NUM', 'ST_NAME', 'ST_NAME_SU', 'UNIT_NUM',
       'ZIPCODE', 'LU', 'PTYPE', 'LOTSIZE', 'MAIL_ADDRE', 'MAIL_CS',
       'MAIL_ZIP', 'OWN_OCC', 'GROSS_AREA', 'BLDG_AREA', 'AV_TOTAL', 'AV_LAND',
       'AV_BLDG', 'GROSS_TAX', 'NUM_FLOORS', 'PID_LONG', 'FULL_ADDRE', 'CITY',
       'STArea__', 'STLength__', 'Shape_STAr', 'Shape_STLe', 'LU_GENERAL',
       'TC_ID', 'Shape_Leng', 'OBJECTID', 'TC_ID_1', 'Total_A', 'Can_A',
       'Grass_A', 'Soil_A', 'Water_A', 'Build_A', 'Road_A', 'Paved_A',
       'Perv_A', 'Imperv_A', 'Can_P', 'Grass_P', 'Soil_P', 'Water_P',
       'Build_P', 'Road_P', 'Paved_P', 'Perv_P', 'Imperv_P', 'OBJECTID_1',
       'TC_ID_12', 'VALUE_0', 'TC_E_A', 'TC_Pv_A', 'TC_Land_A', 'TC_Pi_A',
       'TC_P_A', 'TC_E_P', 'TC_Pv_P', 'TC_P_P', 'TC_Pi_P', 'Shape__Area',
       'Shape__Length'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173875 entries, 0 to 173874
Data columns (total 72 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   FID            173875 non-null  int64
 1   FID_Boston     173875 non-null  int64
 2   BOSTON_LAN     173875 non-null  int64
 3   FID_COB_FY     173875 non-null  int64
 4   PID            173875 non-null  object
 5   CM_ID          173875 non-null  object
 6   GIS_ID         173875 non-null  object
 7   OWNER          173875 non-null  object
 8   ST_NUM         173875 non-null  object
 9   ST_NAME        173875 non-null  object
 10  ST_NAME_SU     173875 non-null  object
 11  UNIT_NUM       173875 non-null  object
 12  ZIPCODE        173875 non-null  object
 13  LU             173875 non-null  object
 14  PTYPE          173875 non-null  object
 15  LOTSIZE        173875 non-null  int64
 16  MAIL_ADDRE     173875 non-null  object
 17  MAIL_CS        173875 non-null  object
 18  MAIL_ZIP       173875 non-null  object
 19  OWN_OCC        173875 non-null  object
 20  GROSS_AREA     173875 non-null  int64
 21  BLDG_AREA      173875 non-null  int64
 22  AV_TOTAL       173875 non-null  int64
 23  AV_LAND        173875 non-null  int64
 24  AV_BLDG        173875 non-null  int64
 25  GROSS_TAX      173875 non-null  float64
 26  NUM_FLOORS     173875 non-null  float64
 27  PID_LONG       173875 non-null  object
 28  FULL_ADDRE     173875 non-null  object
 29  CITY           173875 non-null  object
 30  STArea__       173875 non-null  float64
 31  STLength__     173875 non-null  float64
 32  Shape_STAr     173875 non-null  float64
 33  Shape_STLe     173875 non-null  float64
 34  LU_GENERAL     173875 non-null  object
 35  TC_ID          173875 non-null  int64
 36  Shape_Leng     173875 non-null  float64
 37  OBJECTID       173875 non-null  int64
 38  TC_ID_1        173875 non-null  int64
 39  Total_A        173875 non-null  int64
 40  Can_A          173875 non-null  int64
 41  Grass_A        173875 non-null  int64
 42  Soil_A         173875 non-null  int64
 43  Water_A        173875 non-null  int64
 44  Build_A        173875 non-null  int64
 45  Road_A         173875 non-null  int64
 46  Paved_A        173875 non-null  int64
 47  Perv_A         173875 non-null  int64
 48  Imperv_A       173875 non-null  int64
 49  Can_P          173875 non-null  float64
 50  Grass_P        173875 non-null  float64
 51  Soil_P         173875 non-null  float64
 52  Water_P        173875 non-null  float64
 53  Build_P        173875 non-null  float64
 54  Road_P         173875 non-null  float64
 55  Paved_P        173875 non-null  float64
 56  Perv_P         173875 non-null  float64
 57  Imperv_P       173875 non-null  float64
 58  OBJECTID_1     173875 non-null  int64
 59  TC_ID_12       173875 non-null  int64
 60  VALUE_0        173875 non-null  int64
 61  TC_E_A         173875 non-null  int64
 62  TC_Pv_A        173875 non-null  int64
 63  TC_Land_A      173875 non-null  int64
 64  TC_Pi_A        173875 non-null  int64
 65  TC_P_A         173875 non-null  int64
 66  TC_E_P         173875 non-null  float64
 67  TC_Pv_P        173875 non-null  float64
 68  TC_P_P         173875 non-null  float64
 69  TC_Pi_P        173875 non-null  float64
 70  Shape__Area    173875 non-null  float64
 71  Shape__Length  173875 non-null  float64
dtypes: float64(22), int64(31), object(19)
memory usage: 95.5+ MB

## Formulas and Definitions for Calculations



**Public Parcels:** is any parcel of land that is owned by the City of Boston. Includes,
* City of Boston
* Boston Water and Sewer Commission
* Boston Housing Authority
* Boston Public Schools*
* Boston Redevelopment Authority
* Boston Planning and Development Agency
* Commonwealth of Massachusetts


**Private Parcels:** is any parcel of land that is not owned by the City of Boston

**Percentage of Tree Canopy of Public Parcels**  $$\frac{\text{Total Tree canopy existing area classifed as Public}}{\text{Total Tree canopy existing area}}$$


**Percentage of Tree Canopy of Private Parcels** $$\frac{\text{Total Tree canopy existing area classifed as Private}}{\text{Total Tree canopy existing area}}$$

**TC_E_A:** Tree canopy existing area. The area of tree canopy present when viewed from above using aerial or satellite imagery, excluding water.

## INCLUDES ALL CITY OWNED PROPERTY, SOURCED FROM CITY ORDINANCES 2023:
https://www.boston.gov/sites/default/files/file/2024/01/City%20of%20Boston%20Chapter%2014%20of%20the%20Ordinances%20of%202023%20-%20Ordinance%20Establishing%20Protections%20for%20the%20City%20of%20Boston%20Tree%20Canopy%20-%20City%20Clerk%20signature.pdf

## Exploring the Data

In [ ]:
# Count the number of Parcels of land by unique owners
owner_count = df['OWNER'].value_counts().to_frame(name='Count').reset_index()

# Standardize the names of the owners to be all uppercase
owner_count['OWNER'] = owner_count['OWNER'].str.upper()

owner_count.head(20)

                           OWNER  Count
0                 CITY OF BOSTON   2007
1          CITY OF BOSTON BY FCL    415
2           COMMONWEALTH OF MASS    226
3     TRUSTEES OF BOSTON COLLEGE    203
4       BOSTON HOUSING AUTHORITY    201
5      MARKETPLACE LOFTS LIMITED    162
6               COMMWLTH OF MASS    144
7    RELATED LOVEJOY RESIDENTIAL    133
8      BOSTON REDEVELOPMENT AUTH    132
9         BUCKMINSTER HOTEL CORP    132
10  MASS BAY TRANSPORTATION AUTH    130
11         160 FEDERAL OWNER LLC    123
12    BOSTON UNIVERSITY TRSTS OF    102
13          MASS BAY TRANSP AUTH     97
14    MARRIOTT OWNERSHIP RESORTS     84
15            TRUSTEES OF BOSTON     81
16          DUDLEY NEIGHBORS INC     80
17       NORTHEASTERN UNIVERSITY     80
18  MASSACHUSETTS PORT AUTHORITY     76
19              121 PORTLAND LLC     76

In [5]:
unique_owners = df[df['OWNER'].str.contains("BOSTON", case=False, na=False)]["OWNER"].unique()
unique_owners #631 results for just BOSTON

array(['CITY OF BOSTON BY FCL', 'CITY OF BOSTON',
       'EAST BOSTON NEIGHBORHOOD', 'BOSTONIAN CONSTRUCTION',
       'EAST BOSTON AOP LLC', 'EXCEL ACADEMY E BOSTON RLTY',
       'BOSTON REDEVELOPMENT', 'EAST BOSTON SAVING BANK',
       'HVV EAST BOSTON LLC', 'ROMAN CATH ARCH BOSTON',
       '17 WHITE STREET BOSTON LLC', 'EAST BOSTON AREA PLANNING',
       'EAST BOSTON MANAGEMENT &', 'RRP EAST BOSTON ONE LLC',
       'BOSTON REDEVELOPMENT AUTHOR', 'BOSTON NATURAL AREAS FUND',
       'BOSTON COMMUNITY PROPERTIES', 'LINEAR RETAIL BOSTON #23',
       'LINEAR RETAIL BOSTON #21 LLC', 'LINEAR RETAIL BOSTON #19 LLC',
       'LINEAR RETAIL BOSTON #18 LLC', 'E BOSTON NEIGHBORHOOD HEALTH',
       'CITY OF BOSTON PARKS AND', 'EAST BOSTON MANAGEMENT',
       'BOSTON SAWYERS FAMILY TRUST', 'EAST BOSTON YACHT CLUB',
       'BOSTON MARINE WORKS', 'BOSTON MARINE WORKS INC',
       'EAST BOSTON COMMUNITY', 'EAST BOSTON AIRPORT LLC',
       'BOSTON MAJORDOMO LLC', 'CITY OF BOSTON PARKS COMM',
       'BOSTON HOUSING AUTHORITY', 'BOSTON HOUSING AUTH',
       'TRINITY EAST BOSTON TWO LP', 'EAST BOSTON SOCIAL CENTER IN',
       'EAST BOSTON SAVINGS BANK', 'E BOSTON MANAGEMENT &',
       'EAST BOSTON SAVNGS BNK', 'S-BNK EAST BOSTON LLC',
       'EAST BOSTON NEIGHBORHOOD HEA', 'EAST BOSTON MGMT AND DEVLOP',
       'EAST BOSTON COMMUNITY HEALTH', 'E BOSTON MOHAWK ATHLETIC',
       'BOSTON REDEVELPMENT AUTH', 'BOYS CLUB OF BOSTON MASS',
       'BOYS CLUB OF BOSTON', 'BOSTON EDISON CO',
       'BOSTON REDEVELOPMNT AUTH', 'BOSTON REDEVELOPMENT AUTH',
       'BOSTON AUTOPORT LLC (LESSEE)', 'BOSTON WATER & SEWER',
       'BOSTON EDISON COMPANY', 'BOSTON PAPER BOARD CORP',
       'BOSTON SAND & GRAVEL COMPANY', 'BOSTON SAND & GRAVEL CO',
       'SHAVER BOSTON INVESTMENTS', 'BOSTON REDVLPMNT AUTH',
       'BOSTON SAND AND GRAVEL CO', 'THE BOSTON SYNAGOGUE',
       'BEVERLY-BOSTON LP', 'GREATER BOSTON LEGAL SERVICE',
       'BOSTON HAYMARKET ACQUSITIONS', 'LAZ BOSTON COMMUTER LOTS LLC',
       'CHRIST CHURCH IN BOSTON', 'CITY OF BOSTON TRST',
       'VILLAGGIO BOSTON LLC', 'LINEAR RETAIL BOSTON #15 LLC',
       'CITY OF BOSTON DPW', 'BOSTON REDEVLPMNT AUTH',
       'BOSTON EDISON CO MASS', 'BOSTON REDEVLPMNT AUTHOR',
       'CITY OF BOSTON PWD', 'BOSTON VIEW CORP', 'FORTY COURT BOSTON',
       'HISTORIC BOSTON INC', 'ONE BOSTON PLACE LLC',
       'BOSTON CORNHILL LLC', 'BOSTON TEA PARTY INC',
       'BOSTON BOAT BASIN LLC', 'BOSTON WORSHIP CENTERS',
       'CARAS BOSTON REALTY LLC', 'JH BOSTON LLC', 'AAA BOSTON RE LLC',
       'ROMAN CATH ARCH OF BOSTON', 'BOSTON PORT * SEAMENS',
       'BOSTONIAN HOTEL ASSOCS LPS', 'BOSTONIAN HOTEL LP',
       'THE BOSTONIAN SOCIETY', 'PONTE GADEA BOSTON LLC',
       'DIAMOND ROCK BOSTON BROAD ST', 'ATLANTIC BOSTON CORP',
       'TRPF 99/101 BOSTON OFFICE', 'BOSTON EDISON CO MASS CORP',
       'UNION CLUB OF BOSTON INC', 'PROP BOSTON ATHENAUEM',
       'OMNI BOSTON CORP', 'THI VI BOSTON LLC', 'BOSTON OPERA HOUSE',
       'ACTION FOR BOSTON COMMUNITY', 'BOSTON REDEVELPMNT AUTH',
       'BOSTON THERMAL CORP', 'BOSTON CHINATOWN',
       'CHURCH OF BOSTON EVANGELICAL', 'BOSTON CHINESE EVANGELICL CH',
       'BOSTON  REDEVELOPMENT', 'CITY  OF  BOSTON',
       'BOSTON REDEVLOPMENT AUTHORIT', 'BOSTON REDEVOPMENT AUTH',
       'BOSTON NATURAL AREAS NETWORK', '1000 WASHINGTON (BOSTON)',
       'JACE BOSTON LLC', 'PRIME STORAGE BOSTON', 'SHERATON BOSTON CORP',
       'HADAR BOSTON LLC', 'PIM BOSTON BACK BAY LLC',
       'BOSTON SYMPHONY ORCH INC', 'BOSTON SYMPHONY ORCHESTRA',
       'BOSTON NATURAL AREAS FUND IN', 'BOSTON REHAB ASSOCS I LPS',
       'BOSTON CONSERVATORY RLTY CP', 'BOSTON CONSERV OF MUSIC',
       'BOSTON CONSERVATORY OF MUSIC', 'BOSTON CONSERVATORY',
       'BOSTON CONSERVATRY MUSIC', 'HELLENIC ASSN OF BOSTON',
       'BOSTON PLAYHOUSE RLTY INC', 'BOSTON CHINESE CHURCH',
       'BOSTON REDVLPMNT AUTHOR', 'BOSTON CENTER FOR',
       'BOSTON CENTER FOR THE ARTS', 'MARIST FATHERS OF BOSTON',
       'BOSTON DEVELOPMENTS INC', 'BOSTON BLUE LLC',
       'TRINITY CHURCH IN BOSTON', 'BOSTON UNIVERSITY TRST',
       'OLD SO CHURCH IN BOSTON', 'FIRST CHURCH IN BOSTON',
       'CLUB OF ODD VOLUMES BOSTON', 'LINEAR RETAIL BOSTON #8 LLC',
       'FRENCH LIBRARY IN BOSTON', 'FAL BOSTON LLC',
       'BOSTON ARCHITECTURAL COLLEGE', 'TRIBECA APL BOSTON LLC',
       'K P GROUP BOSTON 217 LLC', 'BOSTON UNIVERSITY TRSTS',
       'BOSTON UNIVERSITY TRSTS OF', 'TRUSTEES OF BOSTON UNIV',
       'BOSTON UNIVRSTY TRSTS OF', 'BOSTON UNIVERSITY TRST OF',
       'BOSTON UNIVERSITY TRS OF', 'BOSTON UNIVERSITY TRS',
       'TRUSTEES OF BOSTON', 'HARVARD CLUB OF BOSTON',
       'S-BNK BOSTON KENMORE LLC', 'TRUSTEES OF BOSTON UNI',
       'TRUSTEES BOSTON UNIVERSITY', 'BOSTON UNIVERSITY TRUSTEE OF',
       'BOSTON UNIVERSITY TS OF', 'BOSTON UNIVERSITY TRUSTEES',
       'TRSUTEES OF BOSTON UNIVERSIT', 'TRUSTEES OF BOSTON UNIVERSIT',
       'BOSTON UNIVERSITY TRSTS THE', '60 KILMARNOCK (BOSTON) OWNER',
       'BOSTON PINNACLE PROPERTIES', 'SOUTH BOSTON BROADWAY',
       'SOUTH BOSTON COMMUNITY HOUSI', 'SOUTH BOSTON NEW HOUSING LLC',
       'SOUTH BOSTON COMM HEALTH', 'SO BOSTON LITHUANIAN',
       'SOUTH BOSTON COMMUNITY', 'SOUTH BOSTON NON PROFIT',
       '5514 D STREET 320 BOSTON LLC', '5515 D STREET 339 BOSTON LLC',
       'SOUTH BOSTON VETERANS', 'MCLOUGHLIN SOUTH BOSTON',
       'SOUTH BOSTON SAVINGS BNK', 'S-BNK SOUTH BOSTON LLC',
       'SOUTH BOSTON SAVINGS BANK', 'LISHAN SOUTH BOSTON TRUST',
       'BLAIR CAPITAL OF BOSTON LLC', 'BOSTON REDEVELOPMENT LLC',
       'SOUTH BOSTON BAPTIST CH', 'HHLP BOSTON SEAPORT',
       'BOSTON SEAPORT M1&2 LAND', 'BOSTON SEAPORT M1&2 LAND LLC',
       'NORWICH PARTNERS BOSTON LLC', 'BOSTON SPARKS ASSN INC',
       'HP BOSTON PARTNERS LLC', 'ALLURE BOSTON LLC',
       'DISCOVER BOSTON MULTI-LINGU', 'KOURIDIS SOUTH BOSTON LLC',
       'COSTELLO BOSTON LLC', 'SO BOSTON POST 6536',
       'SOUTH BOSTON POST NO 6536', 'SOUTH BOSTON POST #6536',
       'BOSTON-SOUTHAMPTON LLC', 'PRIME STORAGE SOUTH BOSTON',
       'BOSTON WARD LLC', 'SOUTH BOSTON NEIGHBORHOOD', 'EIG BOSTON LLC',
       'SOUTH BOSTON AUTO TECH INC', 'BOYS CLUB OF BOSTON INC MASS',
       'BOYS CLUB BOSTON INC MASS', 'BOSTON TECHNOLOGY AND',
       'S BOSTON NEIGHBORHOOD DEV CP', 'REAL ESTATE BOSTON LLC',
       'BOSTON HARBOR YACHT CLB', 'SOUTH BOSTON YACHT CLUB',
       'ROM CATH ARCH OF BOSTON', 'LEE BOSTON TS',
       'BOSTON COLLEGIATE CHARTER', '224 BOSTON STREET DORCHESTER',
       'ROMAN CATHOLIC ARCH BOSTON', '184 BOSTON STREET LLC',
       'ONE 80 BOSTON ST LLC', 'ONE 74 BOSTON ST LLC',
       'ONE40-142 BOSTON ST RLTY LLC', 'BOSTON STREET 2-6 LLC',
       'NINE BOSTON STREET LLC', 'FORTRESS-BOSTON CORPORATION',
       '115 BOSTON STREET LLC', 'ONE-15 BOSTON STREET LLC',
       'ONE-15 BOSTON ST LLC', 'BOSTON COMMON HOLDINGS LLC',
       'CITY OF BOSTON - DND', 'BOSTON NATURAL AREA FUND',
       'CITY OF BOSTON FCL', 'APOSTOLIC CHURCH BOSTON',
       'CITY OF BOSTON FCL.', 'GREEN BOSTON OPERATIONS',
       'BOSTON REDVELOPMENT AUTH', 'BOSTON REDEVLOPMENT AUTH',
       'NEW BOSTON FOOD MARKET', 'BOSTON RD LLC', 'TRUSTEES OF BOSTON U',
       'BOSTON TOPEKA ST LLC', 'BOSTON FLOWER EXCHANGE LLC',
       'BOSTON PUBLIC HEALTH COMM', 'BOSTON MEDICAL CENTER',
       'CITY OF BOSTON (POLICE)', 'CITY OF BOSTON (POLICE DEPT)',
       'BOSTON MEDICAL CENTER CORP', 'BOSTON WATER & SEWER COMM',
       'BOSTON WATER AND SEWER', 'BOSTON MISSIONARY BAPTIST CH',
       'BOSTON MISSIONARY BAPTIST', 'BOSTON RENTAL PROPERTIES LLC',
       'FAIRFIELD BOSTON APTS LPS', 'BOSTON MULTI FAMILY PROPERTY',
       '1027 TREMONT ST BOSTON REAL', 'BOSTON REDEVELOPEMENT AUTH',
       'CENTRAL BOSTON ELDER SERVICE', 'FIRST NATIONAL BANK BOSTON',
       'METRO BOSTON ALIVE INC', 'ISLAMIC SOCIETY OF BOSTON TR',
       'BOSTON NATURL AREAS FUND INC', 'BOSTON SOCIETY REDEMPTORIST',
       'BOSTON REDEVELOP AUTHORITY', 'S-BNK BOSTON LNA LLC',
       'BOSTON BUILDING MATERIALS', 'CITY OF BOSTON SCHOOL DEPT',
       'NATIVITY - BOSTON INC', 'NATIVITY-BOSTON INC',
       'CITY OF BOSTON MUNICIPAL CP', 'CS9 BOSTON C LLC',
       'BOSTON ISLAMIC CENTER INC', 'NATIVITY BOSTON INC',
       'CITY OF BOSTON PUBLIC FACLTS', 'BOSTON NATURAL AREAS',
       'BOSTON LUXURY GROUP LLC', 'ROMAN ARCH OF BOSTON',
       'THIRTY 1 BOSTON LLC', 'BOSTON DAY & EVENING ACADEMY',
       'YMCA OF GREATER BOSTON', 'BOYS CLUB OF BOSTON THE',
       'HABITAT FOR HUMANITY BOSTON', 'BRIDGE BOSTON CHARTER SCHOOL',
       'CITY OF BOSTON PARKS', 'HEA BOSTON LLC',
       'BOSTON RESCUE MISSION INC', 'CITY OF BOSTON MUNICIPAL',
       'BOSTON APARTMENTS LLC', 'BOSTON AOARTMENTS LLC',
       'BOSTON NATURAL AREA FUND INC', 'MERENGUE BOSTON LLC',
       'BOSTON BAY', 'S & H BOSTON REALTY LLC', 'BOSTON COLLEGE HIGH',
       'BOSTON BD LLC', 'CITY OF BOSTON (FCL)',
       'BOSTON NATUAL AREAS NETWORK', 'FAMILY AID BOSTON INC',
       'FAMILY AID OF BOSTON', 'BOSTON AGING CONCERNS YOUNG',
       'BOSTON COMMUNITY COOPERATIVE', 'CITY OF BOSTON PARKS/REC',
       'MATTHEW 25 OF GREATER BOSTON', 'BOSTON RONELDA',
       'LENA NEW BOSTON LLC', 'BOSTON URBAN GARDENERS INC',
       'BOSTON COMMUNITY COOPERA-', 'CITY OF BOSTON DND',
       'BOSTON HAMILTON HOUSE INC', 'BOSTON REAL PROPERTIES LLC',
       'CITY OF BOSTON PUB FACIL', 'FAMILYAID BOSTON INC',
       'BOSTON POLICE PATROLMENS', 'FIVE 38 TALBOT AV BOSTON INC',
       'CITY OF BOSTON CREDIT UNION', 'BOSTON WINERY REAL ESTATE',
       'BOSTONIAN FOUNDATION INC', 'SHOLES BOSTON LLC',
       'BOSTON FIREFIGHTERS CREDIT', 'BOSTON FIREFIGHTERS CRED UN',
       'BOSTON RESTORE INC', 'CAO DAI TEMPLE OF BOSTON INC',
       'BOSTON PROPERTY HOLDINGS LLC', 'DYH BOSTON NOMINEE TRUST',
       'THIRTY-ONE BOSTON LLC', 'BOSTON PROJECT PROPERTIES',
       'GREATER BOSTON YMCA INC', 'YMCA OF GREATER BOSTON INC',
       'GREATER BOSTON YOUNG MENS', 'BOSTON CITY LLC',
       'BOSTON CENTER FOR BLIND', 'BOSTON HOME FOR INCURABLE',
       'BOSTON Y M C A', 'BOSTON PROVINCE OF THE',
       'CITY OF BOSTON PUBLIC HEALTH', 'CITY OB BOSTON PUBLIC HEALTH',
       'HOUR HOUSE BOSTON', 'KIPP BOSTON FUND INC',
       'BOSTON ASSEMBLY OF GOD CHRCH', 'BOSTON CATHOLIC CEMETERY',
       'BOSTON CATH CEMETERY ASSOC', 'BOSTON CATH CEMETERY ASSN',
       'BOSTON CATH CEMETRY ASSN', 'BOSTON CATH CEMETARY ASSN',
       'BOSTON CATH CEMETARY', 'TACBOSTON ASSOCIATES LLC',
       'GREATER BOSTON ACQUISITIONS', 'BOSTON POLICE DETECTIVE',
       'BOSTON CLEARANCE CAPITAL INC', 'BOSTON REDEVELPOMENT AUTH',
       'BOSTON RENAISSANCE CHARTER', 'BOSTON BAPTIST COLLEGE',
       'BOSTON BAPIST COLLEGE', 'BOSTON TRINITY ACADEMY CORP',
       'BOSTON TRINITY ACADEMY INC', 'POODLEMIX BOSTON LLC',
       'FIRST NAT BANK BOSTON', 'BOSTON TRUST & INVESTMENT',
       'SHOWA BOSTON INSTITUTE', 'BOSTON MULTI-FAMILY',
       'CITY OF BOSTON PARKS & REC', 'LINEAR RETAIL BOSTON #20 LLC',
       'EMERALD SOC OF BOSTON', 'BOSTON YOUNG MENS ASSOC',
       'CITY OF BOSTON PFD', 'CITY OF BOSTON CONSERVATION',
       'BOSTON MEDICAL MGT INC TS', 'LINEAR RETAIL BOSTON #22 LLC',
       'KOLLEL OF GREATER BOSTON INC', 'BOSTON NATURAL AREAS FND INC',
       'BOSTON CATH CEM ASSOC', 'BOSTON REDEVELOPMENT AUTHORI',
       'BOSTON LODGE NO 10', 'U-HAUL CO OF BOSTON INC',
       'CITY OF BOSTON PUBLIC WORKS', 'EBENEZER CHURCH OF BOSTON',
       'CITY OF BOSTON (PARK)', 'BOSTON UNIVERSITY TR OF',
       'BOSTON UNIV TRSTS OF', 'BOSTON UNIVSTY TRST OF',
       'BOSTON UNIVERSITY', 'TRUSTEES OF BOSTON UNIVERITY',
       'TRSTS OF BOSTON UNIVERSITY', 'BOSTON BLT LLC', 'CS9 BOSTON B LLC',
       'BOSTON 168 ALLSTON STREET', 'BOSTON REAL ESTATE PORTFOLIO',
       'BOSTON HOUSING AUTHOURTY', 'BOSTON COLLEGE TRUSTEES OF',
       'TRUSTEES OF BOSTON COLLEGE', 'TRUSTEES BOSTON COLLEGE',
       'BOSTON COLLEGE TRS OF', 'BOSTON COLLEGE TRSTS OF',
       'BOSTONIAN REALTY LLC', 'AHAVAT HESSED OF BOSTON INC',
       'BOSTON UNION STREET 26 LLC', 'CITY OF BOSTON LIBRARY DEPT',
       'THE SKATING CLUB OF BOSTON', 'BOSTON LOCK & SAFE CO',
       'BOSTON LANDING LLC', 'MESVITA OF GREATER BOSTON',
       'MESIVTA OF GREATER BOSTON', 'MESIVTA OF GREATER BOSTON IN',
       'BOSTON REHAB ASSOC GP', 'CENTRAL BOSTON CONGREGATION',
       'BOSTON UNITED PENTECOSTAL', 'FIRST NTL BANK OF BOSTON',
       'TRSTS OF BOSTON COLLEGE', 'FEDERAL RESRVE BNK OF BOSTON',
       'BOSTON BAR FOUNDATION INC', 'BOSTON CHINESE EVANGELICAL',
       'BOSTON HOSPITAL FOR WOMEN', 'CONG ADATH ISRAEL OF BOSTON',
       'COMMUNITY CHURCH OF BOSTON', 'GUILD OF BOSTON ARTISTS',
       'BOSTON AUTOPART LLC (LESSEE)', '1 LOVEJOY WHARF BOSTON',
       'CITY OF BOSTON FIRE DEPARTME', 'BOSTON RETAIL INVESTMENT LP',
       'BOSTON BAR FOUNDATION', 'JUNIOR LEAGUE OF BOSTON',
       'TRUSTESS OF BOSTON', 'BOSTON UNIV TRSTS MTGEE',
       'THE BOSTON CONSERVATORY', 'BOSTON WATER AND SEWER COMM',
       'BOSTON POLICE POST 1018 VFW', 'BOSTON SOCIETY OF VULCANS',
       'BOSTON UNIV TRSTS OF MTGEE', 'SOUTH BOSTON COMM HEALTH CTR',
       'BOSTON HARBOR INDUSTRIAL', 'BOSTON AGING YOUNG & OLD INC',
       'BOSTON GUN AND RIFLE ASSOC', 'BOSTON SOCIETY OF VULCANS OF',
       'BOSTON ELKS LODGE, BOSTON', 'BOSTON TRAILER PARK TENTANTS',
       'BOSTON TRAILER PARK TENANTS', 'BOSTON UNIVERSITY TRUST',
       'BOSTON SKYE PROPERTIES LLC', 'ROYAL BOSTON TRUST',
       'WASHINGTON ST BOSTON LP', 'ARCHSTONE BOSTON COMMON',
       'BOSTON GARDEN DEVELOPMENT', 'BOSTON PUBLIC MARKET',
       'CHSP BOSTON II LLC', 'LINEAR RETAIL BOSTON #5 LLC',
       'PROPRIETORS OF THE BOSTON', 'LINEAR RETAIL BOSTON #24 LLC',
       'ROCKLAND BOSTON CONDOMINIUM', 'BOSTON 1927 OWNER LLC',
       'BOSTON ARTICTECTURAL COLLEGE', 'LINEAR RETAIL BOSTON #12 LLC',
       'BOSTON CARPENTERS TRAINING', 'YOUTHBUILD BOSTON INC',
       'BOSTON BUILDING MATERIALS CO', 'COMMITTEE FOR BOSTON',
       'BOSTON SIOBHAN M', 'BOSTON WILSIUS LLC',
       'EARL OF SANDWICH BOSTON LLC', 'FIVE 85 BOSTON OFFICE LLC',
       'COPLEY SOCIETY OF BOSTON', 'XHR BOSTON COMMONWEALTH',
       'ONE SIXTY SIX BOSTON STREET', 'ONE-64 BOSTON STREET',
       'ONE-32 BOSTON ST CONDO TRUST', 'ONE-06 BOSTON STREET CONDO',
       'ONE 04 BOSTON ST CONDO', 'ONE 02 BOSTON ST CONDO TR',
       '30 BOSTON STREET CONDOMINIUM', 'ELEVEN BOSTON ST CONDO TR',
       '155 BOSTON STREET', 'TWO-35 BOSTON ST CONDO TRUST',
       'TWO-41 BOSTON ST CONDO TR', 'METROPOLITAN BOSTON HOUSING',
       'BOSTON CITY DEVELOPERS LLC', 'BOSTON SAUSAGE COMPANY LLC',
       'TOWNHOMES AT BOSTON ROCK', 'CK OF BOSTON LLC',
       'BOSTON 112 PRINCE STREET #2', 'BOSTON HARBORSIDE SUITES',
       'BOSTONNE LLC', 'BOSTON NE LLC', 'RISLEY WHELTON REALTY BOSTON',
       'M & R BOSTON ASSOCIATES LLC', 'BOSTON BROWNSTONE REALTY',
       'KFT BOSTON LLC', 'LINEAR RETAIL BOSTON #14 LLC',
       'LINEAR RETAIL BOSTON #10 LLC', 'LINEAR RETAIL BOSTON #16 LLC',
       'BOSTON BROWNSTONE 4 REALTY', 'TWENTY 8 BOSTON ST CONDO TR',
       'TWENTY 6 BOSTON ST CONDO TR', 'BOSTON PUBLIC HEALTH',
       'PHIPPS BOSTON 1 LLC', 'PHIPPS BOSTON 2 LLC',
       'PHIPPS BOSTON 3 LLC', 'PHIPPS BOSTON 4 LLC',
       'ONE 05 PRINCE ST AT BOSTON', 'BOSTON LLC', 'BOSTONIAN LLC',
       'GREATER BOSTON YMCA', 'S&D BOSTON PROPERTIES LLC',
       'BOSTON SSSA LLC', 'PARTHELON BOSTON LLC',
       'BOSTON REALTY HOLDINGS LLC', 'SIBAST PROPERTIES BOSTON INC',
       'MMBOSTON LLC', 'BOSTON UNIV TRUSTEES OF',
       'MCB SOUTH BOSTON DEVELOPMENT', 'OLD BOSTON RESTORATIONS INC',
       'POWERHAUS OF BOSTON LLC', 'WORCESTER STREET BOSTON LLC',
       'BOSTON REAL ESTATE GROUP LLC', 'JUICE BOSTON LLC',
       'BOSTON DEVELOPMENT', 'EIGHT BRIMMER ST BOSTON LLC',
       'LDK BOSTON PROPERTIES LLC', 'BC BOSTON PROPERTY HOLDINGS',
       '246 BOSTON STREET', 'GREETINGS FROM BOSTON', 'THE BOSTON SOCIETY',
       'MEYER BOSTON REALTY TRUST', 'OMSHIVAM-BOSTON LLC',
       'BOSTON VIEW ASSOC LLC', 'LINEAR RETAIL BOSTON #2 LLC',
       'SIXTH FLOOR BOSTON LLC', 'LINEAR RETAIL BOSTON #3 LLC',
       'BOSTON CITY LIGHTS FOUNDATON', 'LINEAR RETAIL BOSTON #9 LLC',
       'BOSTON GROUP REALTY TRUST', 'S-BNK BOSTON HANOVER LLC',
       'LINEAR RETAIL BOSTON #6 LLC', 'BOSTON PARKING REALTY TRUST',
       'ROSECLAIR BOSTON LLC', 'BOSTON BAY REALTY TRUST',
       'BOSTON ASSETS & CURRENCY CP', 'BOSTON 701 MASSACHUSETTS',
       'LDS BOSTON REALTY LLC', 'SDM BOSTON REALTY TRUST',
       'STECMA BOSTON HOMES LLC', 'T L BOSTON INVESTMENT LLC',
       'A & M BOSTON PROPERTIES LLC', 'BOSTON SMOKED FISH COMPANY',
       'WORLDBOSTON INC', 'BOSTON SOUTH END LLC',
       'COMMONWEALTH BOSTON REALTY', 'BOSTON PARKING REALTY',
       'SOUTH BOSTON 4B LLC', 'QUAIL BROOK BOSTON HOLDINGS',
       'LINEAR RETAIL BOSTON #7 LLC', 'BOSTON VIEW ASSOCIATES LLC',
       'MANCAT BOSTON LLC', 'A&M BOSTON PROPERTIES LLC', 'BOSTON 4E LLC',
       'BOSTON BROAD ST LLC', 'SOLOMON BOSTON PROPERTY',
       'NAIDU LEXINGTON-BOSTON', 'J&A (BOSTON) ASSOCIATES LLC',
       'CARLTON HOUSE OF BOSTON', 'AAF BOSTON 2016 LLC',
       'SEVILLE ON BOSTON HARBOR LLC', '11 PARK DRIVE UNIT 19-BOSTON',
       'BOSTON TOWNHOUSE LLC', 'BOSTON CHARLESVIEW REALTY',
       'BOSTON 113 UNION WHARF INC', 'PHEONIX SERIES BOSTON LLC',
       'RHF BOSTON LP', 'BOSTON APT HOLDINGS LLC',
       'CRK BOSTON PROPERTIES LLC', 'BLUE ANGEL BOSTON CORP',
       'MOSA BOSTON LTD', 'LINEAR RETAIL BOSTON #1 LLC',
       'LINEAR RETTAIL BOSTON #1 LLC', 'BOYLSTON STREET BOSTON TRUST',
       'BOSTON EVENING CLINIC FDN', 'BOSTON WINDSOR LLC',
       'BOSTON MARINER REALTY LLC', 'SILVERSANDS BOSTON LIMITED',
       'PALLIUM BOSTON LIMITED', 'COMMONWEALTH BOSTON RLTY LLC',
       'BOSTON BETTER LIVING LLC', 'J5 BOSTON REALTY LLC',
       'CHARLTON BOSTON J', 'SZETO BOSTON INVESTMENT LLC',
       'BOSTON KENMORE CONDO TR', 'EXTELL BOSTON ATLANTIC LLC',
       'BOSTON SEAPORT LLC', 'AMPEX BOSTON LLC',
       'EXTELL BOSTON RESIDENTIAL', 'UNIT 18N BOSTON LLC',
       'LINEAR RETAIL BOSTON #13 LLC', 'AQUARIUS BOSTON ESTATE LLC',
       'PROVINCE BOSTON REAL ESTATE', 'OMNI BOSTON CORPORATION',
       'BOSTON REALTY OF FLORIDA LLC', 'ELTENLIGHT BOSTON LLC',
       'JOLYON BOSTON LLC', 'BOSTON PROPERTY 1 LLC',
       'BOSTON PROPERTY 2 LLC', 'PHOENIX SERIES BOSTON LLC',
       'BELMONT INVESTMENTS BOSTON', 'VII MP BOSTON HOTEL OWNER A',
       'VII MP BOSTON HOTEL OWNER B', 'TRSUTEES OF BOSTON COLLEGE',
       'TRUSTESS OF BOSTON COLLEGE', 'SALTUS BOSTON LLC',
       'FLAGSHIP WHARF BOSTON LLC', 'BOSTON 3B LLC', 'BAYBANK BOSTON N A',
       'FOLIO BOSTON CONDO TRUST', 'KKH BOSTON LLC',
       'BOSTON MUNICIPAL RESEARCH', 'BOSTON BROAD STREET LLC',
       'KCW BOSTON PROPERTIES LLC', 'LINEAR RETAIL BOSTON #17 LLC',
       'BOSTON MILLENNIUM LLC', 'CML BOSTON REALTY TRUST',
       '580 BOSTON HOLDINGS LLC', 'BEITBOSTON LLC', 'PHA BOSTON PAD LLC',
       'DOCTORS OF SOUTH BOSTON LLC', 'COTTERMAN BOSTON PROPERTIES',
       'BOSTON LINNEAN LLC', 'BOSTON EVENING', 'BOSTON PROPERTY 3 LLC',
       'LUO PAN BOSTON LLC', 'BOSTON GLOBAL VICTORY LLC',
       'BOSTON GLOBAL FORTUNE LLC', 'MILLENNIUM BOSTON REALTY',
       'RMAJ BOSTON LLC', 'BOYLSTON STREET BOSTON',
       'LINEAR RETAIL BOSTON #4LLC', 'LINEAR RETAIL BOSTON #4 LLC',
       'ACTION FOR BOSTON COMMINITY', 'BOSTON MEDICAL REALTY',
       'THE BOSTON CHILDRENS SCHOOL', "THE BOSTON CHILDREN'S SCHOOL"],
      dtype=object)

## Data Cleaning

* Classified roads, sidewalks and streets as public

In [ ]:
# Replace any rows with a ' '  owner with a null
df["OWNER"] = df["OWNER"].replace(" ", pd.NA)

# find all null rows
df[df["OWNER"].isna()]

# Classify the null row owner as 'CITY OF BOSTON', since it represents all roads and sidewalks in Boston
df.loc[df["OWNER"].isna(), "OWNER"] = "CITY OF BOSTON"

## Data Analysis

In [ ]:
#list of owners that are classified as publicly owned
public_owners = {
       # City of Boston
       'CITY OF BOSTON BY FCL', 'CITY OF BOSTON',
       'CITY OF BOSTON PARKS AND', 'CITY OF BOSTON PARKS COMM',
       'CITY OF BOSTON TRST', 'CITY OF BOSTON DPW', 'CITY OF BOSTON PWD',
       'CITY OF BOSTON - DND', 'CITY OF BOSTON FCL',
       'CITY OF BOSTON FCL.', 'CITY OF BOSTON (POLICE)',
       'CITY OF BOSTON (POLICE DEPT)', 'CITY OF BOSTON SCHOOL DEPT',
       'CITY OF BOSTON MUNICIPAL CP', 'CITY OF BOSTON PUBLIC FACLTS',
       'CITY OF BOSTON PARKS', 'CITY OF BOSTON MUNICIPAL',
       'CITY OF BOSTON (FCL)', 'CITY OF BOSTON PARKS/REC',
       'CITY OF BOSTON DND', 'CITY OF BOSTON PUB FACIL',
       'CITY OF BOSTON CREDIT UNION', 'CITY OF BOSTON PUBLIC HEALTH',
       'CITY OF BOSTON PARKS & REC', 'CITY OF BOSTON PFD',
       'CITY OF BOSTON CONSERVATION', 'CITY OF BOSTON PUBLIC WORKS',
       'CITY OF BOSTON (PARK)', 'CITY OF BOSTON LIBRARY DEPT', 'CITY OB BOSTON PUBLIC HEALTH', 'BOSTON PUBLIC HEALTH', 'BOSTON PUBLIC HEALTH COMM',
       'PUBLIC FACILITIES COMM','CITY OF BOSTON FIRE DEPARTME', 'PUBLIC FACILITIES COMM', 'DEPARTMENT OF PUBLIC WORKS', 'TRUSTEES OF PUBLIC LIBRARY',
       # Commonwealth of Massachusetts
      "COMMONWEALTH OF MASS", "COMMWLTH OF MASS",
       # Boston Water and Sewer Commission
      'BOSTON WATER AND SEWER COMM', 'BOSTON WATER AND SEWER', 'BOSTON WATER & SEWER','BOSTON WATER & SEWER COMM',
       # Boston Housing Authority
      'BOSTON HOUSING AUTHORITY', 'BOSTON HOUSING AUTH', 'BOSTON HOUSING AUTHOURTY',
       # Boston Redevelopment Authority
       'BOSTON REDEVELOPMENT LLC', 'BOSTON REDEVELOPMENT AUTHORI','BOSTON REDEVELOPMENT', 'BOSTON REDEVELOPMENT AUTHOR', 'BOSTON REDEVELOPMNT AUTH',
       'BOSTON REDEVELOPMENT AUTH', 'BOSTON REDEVLPMNT AUTH','BOSTON REDEVLPMNT AUTHOR','BOSTON  REDEVELOPMENT',
       'BOSTON REDEVLOPMENT AUTHORIT', 'BOSTON REDEVOPMENT AUTH', 'BOSTON REDEVLOPMENT AUTH',
       'BOSTON REDEVELOPEMENT AUTH', 'BOSTON REDEVELOP AUTHORITY', 'BOSTON REDEVELPOMENT AUTH',
       # Boston Planning and Development Agency
       'BOSTON DEVELOPMENT'
                 }



# Calculate the total TC_E_A(Tree canopy existing area) - total tree canopy that exists in Boston
total_tree_canopy = df["TC_E_A"].sum()

# Create a new column called 'Parcel'
df["Parcel"] = df["OWNER"].apply(lambda x: "Public" if x in public_owners else "Residential")

# Group TC_E_A(Tree canopy existing area) by public/residential
agg_by_parcel = df.groupby("Parcel")["TC_E_A"].sum().reset_index()

# Add total tree canopy to the dataframe
agg_by_parcel["Total Tree Canopy Area"] = total_tree_canopy

# Calculate Percentage of Tree Canopy
agg_by_parcel["Percentage of Total Tree Canopy"] = ((agg_by_parcel["TC_E_A"] / agg_by_parcel["Total Tree Canopy Area"])*100).round(2)

agg_by_parcel

,Parcel,TC_E_A,Total Tree Canopy Area,Percentage of Total Tree Canopy
0,Public,139493193,357959872,38.97
1,Residential,218466679,357959872,61.03